export default {
  'en-us': {
    barText: 'Blog',
    postsTitle: 'All posts',
    list: [
      {
        title: 'Java new feature',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2018',
        desc: 'Java,Java new feature',
        link: '/en-us/blog/java/feature.html',
      },
      {
        title: 'Java Class loading mechanism',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2018',
        desc: 'Java,Java Class loading mechanism',
        link: '/en-us/blog/java/load-class.html',
      },
      {
        title: 'ORM merit and demerit',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2018',
        desc: 'ORM,Orm merit and demerit',
        link: '/en-us/blog/java/orm.html',
      }, 
      {
        title: 'Python new feature',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2018',
        desc: 'Python,Python new feature',
        link: '/en-us/blog/python/feature.html',
      },
      {
        title: 'Python character operation',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2018',
        desc: 'Python,Python character operation',
        link: '/en-us/blog/python/str_joint.html',
      }, 
      {
        title: 'Python syntax rule',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2018',
        desc: 'Python,Python syntax rule',
        link: '/en-us/blog/python/syntax_rule.html',
      },   
      {
        title: 'Data Split',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2019',
        desc: 'Data Split',
        link: '/en-us/blog/sql/data_split.html',
      },  
    ],
  },
  'zh-cn': {
    barText: '博客',
    postsTitle: '所有文章',
    list: [
      {
        title: 'Java 新特性',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2018',
        desc: 'Java,Java 新特性',
        link: '/zh-cn/blog/java/feature.html',
      },
      {
        title: 'Java 类加载机制',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2018',
        desc: 'Java,Java 类加载机制',
        link: '/zh-cn/blog/java/load-class.html',
      },
      {
        title: 'Orm的优缺点',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2018',
        desc: 'Java,Orm的优缺点',
        link: '/zh-cn/blog/java/orm.html',
      }, 
      {
        title: 'Python 新特性',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2018',
        desc: 'Python,Python 新特性',
        link: '/zh-cn/blog/python/feature.html',
      },
      {
        title: 'Python 字符操作',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2018',
        desc: 'Python,Python 字符操作',
        link: '/zh-cn/blog/python/str_joint.html',
      }, 
      {
        title: 'Python 语法技巧',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2018',
        desc: 'Python,Python 语法技巧',
        link: '/zh-cn/blog/python/syntax_rule.html',
      },
      {
        title: '数据库拆分',
        author: 'BurningMyself',
        dateStr: 'May 12nd，2019',
        desc: 'Database Split',
        link: '/zh-cn/blog/sql/sata_split.html',
      },       
    ],
  },
};
